#!/bin/bash
source $PWD/airtome2html.config
git pull
${PWD}/sync-wwwdir.sh
zip -FSrq ${PWD}/${flightbookfilename}.fb.zip ${PWD}/flightbook ${flightbookfilename}.xml
${airtomebin} && unzip -q -o {PWD}/${flightbookfilename}.fb.zip && ${PWD}/sync-wwwdir.sh
