#!/bin/bash
source $PWD/airtome2html.config.sh
git pull
zip -FSrq ${flightbookfilename}.fb.zip flightbook ${flightbookfilename}.xml
${airtomebin} && unzip -q -o ${PWD}/${flightbookfilename}.fb.zip
${PWD}/sync-wwwdir.sh
