#!/bin/bash
source ${PWD}/airtome2html.config.sh
for D in `find ${PWD}/flightbook -type d`
do
  for F in `find $D -type f -iname "*.igc"`
  
  do
    filename=${F}
    #rm spaces
    if [[ "$filename" =~ \ |\' ]]; then
        rename -v 's/ /_/g' $D/*.igc
        filename=${filename/ /_}
    fi 
    
    if [ ! -f "${filename}.kmz" ]; then
      echo $filename
      if  gpsbabel -t -i igc -f "${filename}" -o kml,points=0,trackdirection=1,line_color=${maps_line_color},floating=1,extrude=1,track=0,trackdata=0,line_width=${maps_line_width},max_position_points=${maps_points_count} -F "${filename}.kml"; then
        mkdir $(dirname ${filename})/kmz
        cp ${filename}.kml $(dirname ${filename})/kmz/doc.kml
        zip -rj $(dirname ${filename})/$(basename ${filename}).kmz $(dirname ${filename})/kmz/doc.kml
        rm -rf $(dirname ${filename})/kmz
        rm ${filename}.kml
      else
        echo "${filename} could not be converted to kmz. Skipping ..."
      fi
    fi
  done
done
